services:
    node:
        image: "node:lts-alpine"
        user: "node"
        working_dir: /home/node/app
        volumes:
            - ./server/:/home/node/app
        command: ash -c "npm i && node index.js"
    nginx:
        image: "nginx"
        volumes:
            - ./client:/usr/share/nginx/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/ssl:/etc/nginx/ssl
        ports:
            - "443:443"
